### ISSUE TITLE
Opening application from recent files causes data file error

### ISSUE THREAD

**Issue by yzhilong** [AY2122S1-CS2103-F10-4/tp#163]
I downloaded the file, and opened it from recent files within file explorer, which then causes this error.

![image](https://user-images.githubusercontent.com/44795294/140605786-0e23bc1b-9da6-4779-8362-36ceee94b6d9.png)

![image](https://user-images.githubusercontent.com/44795294/140605768-c2e5c852-8f03-4101-b48d-1eea152f71d6.png)

Opening the app from where the jar file is located does not cause this issue.

**Comment by yatbun** [comment]
Was the application launched by double-clicking on the .jar file or using the command line?

**Comment by yzhilong** [comment]
> Was the application launched by double-clicking on the .jar file or using the command line?

By double clicking it from the recent files dropdown menu

**Comment by yatbun** [comment]
> > Was the application launched by double-clicking on the .jar file or using the command line?
> 
> By double clicking it from the recent files dropdown menu

Do run the jar file according to PE instructions:
- Put the JAR file in an empty folder in which the app is allowed to create files (i.e., do not use a write-protected folder).
- In rare cases, the team could have submitted a ZIP file instead of a JAR file. In that case, unzip that file into the target folder.
- Open a command window. Run the java -version command to ensure you are using Java 11.
- Launch the jar file using the java -jar command rather than double-clicking (reason: to ensure the jar file is using the same java version that you verified above). Use double-clicking as a last resort.
